server:
  port: 8060
spring:
  application:
    name: record-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: route_thirdparty # 题目微服务路由规则
          uri: lb://record-thirdparty # 负载均衡，将请求转发到注册中心注册的record-thirdparty服务
          predicates: # 断言
            - Path=/api/thirdparty/** # 如果前端请求路径包含 api/thirdparty，则应用这条路由规则
          filters: #过滤器
            - RewritePath=/api/(?<segment>.*),/$\{segment} # 将跳转路径中包含的api替换成空